const API_ROOT = 'http://139.162.159.44:3000'

const PROJECTS_ENDPOINT ='/projects'

const TODOLIST_ENDOPOINT = '/to_do_lists'

export const PROJECT_URL = API_ROOT + PROJECTS_ENDPOINT
export const TODOLIST_URL = API_ROOT + TODOLIST_ENDOPOINT